# yamllint disable rule:line-length
---

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}-family.yml"

- name: Include Distribution version specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: Include tasks
  include_tasks: "os_specific/{{ ansible_distribution }}.yml"

- name: Include tasks
  include_tasks: "os_specific/{{ ansible_os_family }}-family.yml"

- include_tasks: repo.yml
  when: not tmux_install_from_source|bool

- include_tasks: set_user_list.yml
  when: >
    tmux_user_config|bool or
    tmux_user_install|bool

- name: Installing config
  include_tasks: config.yml

- name: Setting user_list (global)
  set_fact:
    tmux_user_list:
      root:
        home: "{{ tmux_prefix }}"
        gid: 1000
        uid: 1000
        shell: /bin/bash
  when:
    - not tmux_user_install|bool
    - tmux_install_from_source|bool

- name: Install from source
  include_tasks: source.yml
  loop: "{{ lookup('dict', tmux_user_list, wantlist=true) }}"
  when: tmux_install_from_source|bool
