---
- name: Update cache (Debian)
  become: true
  apt:
    update_cache: true
  tags: molecule-idempotence-notest

- name: Installing build tools
  become: true
  apt:
    name: "{{ build_tools }}"
    state: present
  when: tmux_install_from_source|bool

- name: Installing additionnal dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - autoconf
    - libncurses-dev
    - libevent-dev
    - pkg-config
  when: tmux_install_from_source|bool
