---

- name: Installing build tools
  become: true
  yum:
    name: "{{ build_tools }}"
    state: present

- name: Installing additionnal dependencies
  become: true
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - ncurses-devel
    - libevent
    - libevent-devel
    - pkgconfig
